package com.soldev.kafka_implementation.infrastructure.adapter.in.rest;

import com.soldev.kafka_implementation.autogenerated.events.user.UserCreatedEvent;
import com.soldev.kafka_implementation.infrastructure.adapter.out.KafkaProducer;
import com.soldev.kafka_implementation.infrastructure.adapter.KafkaTopicStatic;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/v1/users")
public class UserController {

    private final KafkaProducer kafkaProducer;

    public UserController(KafkaProducer kafkaProducer) {
        this.kafkaProducer = kafkaProducer;
    }

    @PostMapping
    public void createUser(){
        UserCreatedEvent event = UserCreatedEvent.newBuilder()
                .setId(1L)
                .setFirstname("John")
                .setLastname("Doe")
                .setEmail("test@mail.com")
                .setRole("admin")
                .setTimestamp(System.currentTimeMillis())
                .build();
        kafkaProducer.send(KafkaTopicStatic.USER_CREATED_TOPIC.getTopic(), event);
    }

}
