spring:
  application:
    name: order-service

server:
  port: 8080 # Puerto de la API REST
  servlet:
    context-path: /orders

app:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      # Key: Texto plano (ID de entidad para garantizar orden)
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Value: El serializador de Confluent para Avro
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      # GARANTÍAS DE ARQUITECTURA
      acks: all # Garantía de entrega a todas las réplicas
      properties:
        enable.idempotence: true # Productor idempotente
        schema.registry.url: http://localhost:8081
    #Negocio
    topic: order.created.events