server:
  port: 8082
  servlet:
    context-path: /inventory

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3307/inventory_db?createDatabaseIfNotExist=true # Nota el puerto 3307
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-service-group # Nombre del Consumer Group
      auto-offset-reset: earliest
      # Key: Esperamos el String del ID
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # Value: Deserializador de Confluent para Avro
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true  # Convierte el byte array a tu clase Java autogenerada
    listener:
      # GARANTÍA DE ARQUITECTURA: Control total del commit para Idempotencia
      ack-mode: manual_immediate # Para hacer el commit manualmente tras verificar la idempotencia
    producer: #Dead letter queue config
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081

app:
  kafka:
    topic: order.created.events
